# Generated by Django 4.0.5 on 2022-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('parentezco', models.CharField(max_length=10)),
                ('edad', models.FloatField(max_length=4)),
                ('DNI', models.FloatField(max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
